services:

  db:
    image: postgres
    container_name: markmurphydev_postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Name of the postgres db in the container
      POSTGRES_DB: markmurphydev_dev
    volumes:
      # Place to persist data between container runs
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: postgres://postgres:postgres@db:5432/markmurphydev_dev
      POLYGON_API_KEY: "${POLYGON_API_KEY}"
      # For dev, I think it's fine to have it be public.
      SECRET_KEY_BASE: j+iC8LVnNdLNVHGr5hHjHb6nH2473FB+itBDzkTxlv8gjPW0A4l6NcALF88daSg4
    ports:
      - "4000:4000"
    volumes:
      # Bind mount -- mount ./ on disk (the project folder) into the container at /app
      - .:/app
    # command: iex --dbg pry -S mix phx.server
    command: /bin/bash
    stdin_open: true
    tty: true

volumes:
  db_data:
