services:

  db:
    image: postgres
    container_name: markmurphydev_postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Name of the postgres db in the container
      POSTGRES_DB: markmurphydev_dev
    volumes:
      # Place to persist data between container runs
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
